/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package user_interface.support_agent;

import ecosystem.Ecosystem;
import java.awt.Color;
import javax.swing.JOptionPane;
import user_interface.MainJFrame;

/**
 *
 * @author nishu
 */
public class SupportAgentPanel extends javax.swing.JPanel {

    /**
     * Creates new form SupportAgentPanel
     */
    public SupportAgentPanel(Ecosystem system, MainJFrame mainframe) {
        initComponents();
        jPanel1.setBackground(new Color(0,0,0,15));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblDeliveryAgent2 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setLayout(null);

        jLabel2.setText("Name");

        jLabel3.setText("Employee ID");

        tblDeliveryAgent2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Support ID", "Order ID", "Customer ID", "Customer Phone", "Reason"
            }
        ));
        tblDeliveryAgent2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDeliveryAgent2MouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tblDeliveryAgent2);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(88, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(136, 136, 136)
                        .addComponent(jLabel3)
                        .addGap(129, 129, 129))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 733, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(69, 69, 69))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(39, 39, 39)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(88, Short.MAX_VALUE))
        );

        add(jPanel1);
        jPanel1.setBounds(50, 100, 890, 460);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/customer-support-bg.jpg"))); // NOI18N
        add(jLabel1);
        jLabel1.setBounds(0, 0, 1200, 720);

        jLabel10.setFont(new java.awt.Font("Maku", 3, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 51, 102));
        jLabel10.setText("Welcome Admin ..!!");
        add(jLabel10);
        jLabel10.setBounds(100, 0, 380, 80);
    }// </editor-fold>//GEN-END:initComponents

    private void tblDeliveryAgent2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDeliveryAgent2MouseClicked
        // TODO add your handling code here:
        String message = "Issue Resolved\n";
        Object[] params = {message};
        JOptionPane.showConfirmDialog(null, params, "Update Issue Status", JOptionPane.PLAIN_MESSAGE);
    }//GEN-LAST:event_tblDeliveryAgent2MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable tblDeliveryAgent2;
    // End of variables declaration//GEN-END:variables
}
